"use client"
import type { NextPage } from 'next';
import Head from 'next/head';
// import styles from 'globals.css';
import "./globals.css";
import NowPlaying from '../../components/NowPlaying';

const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <NowPlaying />
      </main>
    </div>
  );
}
export default Home;